### ISSUE TITLE
Unable to upload

### ISSUE THREAD

**Issue by preetampt57** [adobe/aem-upload#84] opened 2022-07-20 11:11 UTC
trying to upload in local AEM server as well ad in the hosted server but nothing is uploading with the following code
       
        const targetUrl = 'http://localhost:4502/content/dam/test';
        const uploadFiles = [
            {
                fileName: 'Wallpaper.png',
                fileSize: 6994,
                filePath: '.\\Wallpaper.png'
            }
        ];

        const upload = new DirectBinary.DirectBinaryUpload();
        const options = new DirectBinary.DirectBinaryUploadOptions()
            .withUrl(targetUrl)
            .withUploadFiles(uploadFiles)
            .withBasicAuth('admin:admin')

        upload.uploadFiles(options)
            .then(result => {
                console.log('result', result);
            }).catch(err => {
                console.log('err', err);
            });

**Comment by mfrisbey** [comment] 2022-07-25 22:09
@preetampt57 thank you for the report. Unfortunately, this is not enough information to diagnose the problem. I would recommend the following:

* Follow the instructions in the [logging](https://github.com/adobe/aem-upload/#logging) section of the documentation so that you can get more information about what the library is doing. I suspect this will give you additional information that you can use to diagnose the problem.
* Listen for the library's [events](https://github.com/adobe/aem-upload/#upload-events). If there are issues uploading individual files, this is where you can get that information.
* The sample you pulled this code from has the following comment: `URL to the folder in AEM where assets will be uploaded. Folder must already exist`. Please ensure that the directory `/content/dam/test` exists in your instance.
* Lastly, the upload process requires specific configurations for a local AEM instance. These configurations are not specified by default, and are out of the scope of this library. If your instance is not configured correctly, the `err` in your `.catch()` statement will have a `err.code` value of `NOT_SUPPORTED`.

I'm closing this issue because it could not be reproduced using the same code, against a local AEM instance that has been configured correctly.

**Closed by mfrisbey** 2022-07-25 22:09 UTC
